name: terratest
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  terratest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/setup-go@v5
      name: Setup Go
      with:
        go-version: '1.23.2'

    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Run test
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: |
        cd test
        go mod download
        go test -v -timeout 5m
